version: "3"
services:
  app:
    build: .
    restart: always
    ports:
      - "3000" # Expose internally only
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://192.168.122.11

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # This is the ONLY port exposed to the outside world
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
